author: c7w
version: 0.5
name: ChatC
main: cf.cc7w.ChatC.ChatC
softdepend: [PlaceholderAPI,Vault]
commands:
  chatc:
    usage: ''
    permission: ''
permissions:
  chatc.admin:
    default: op
  chatc.color:
    default: op
  chatc.help:
    default: op
  chatc.file:
    default: op
  chatc.user:
    default: op
  chatc.info:
    default: true