author: c7w
version: 0.3
name: ChatC
main: cf.cc7w.Chat.Chat
softdepend: []
commands:
  chatc:
    usage: ''
    permission: ''
permissions:
  chatc.admin:
    default: op
  chatc.color:
    default: op